// /lib/colors.js

export const colorSwatches = [
  { name: 'White', hex: '#FFFFFF' },
  { name: 'Black', hex: '#000000' },
  { name: 'Navy', hex: '#000080' },
  { name: 'Royal Blue', hex: '#4169E1' },
  { name: 'Red', hex: '#FF0000' },
  { name: 'Heather Gray', hex: '#BEBEBE' },
  { name: 'Dark Heather', hex: '#555555' },
  { name: 'Sport Gray', hex: '#A7A7A7' },
  { name: 'Kelly Green', hex: '#4CBB17' },
  { name: 'Maroon', hex: '#800000' },
  { name: 'Bright Yellow / Gold', hex: '#FFD300' },
  { name: 'Daisy', hex: '#FFEB3B' },
  { name: 'Orange', hex: '#FFA500' },
  { name: 'Carolina Blue', hex: '#56A0D3' },
  { name: 'Sapphire Blue', hex: '#0F52BA' },
  { name: 'Irish Green', hex: '#00A550' },
  { name: 'Purple', hex: '#800080' },
  { name: 'Sky Blue', hex: '#87CEEB' },
  { name: 'Lime Green', hex: '#32CD32' },
  { name: 'Tropical Pink', hex: '#FF69B4' },
  { name: 'Sand', hex: '#C2B280' },
  { name: 'Natural / Off-White', hex: '#FAF3E0' },
  { name: 'Military Green', hex: '#4B5320' },
  { name: 'Olive Drab', hex: '#6B8E23' },
  { name: 'Forest Green', hex: '#228B22' },
  { name: 'Brown', hex: '#8B4513' },
  { name: 'Tan / Khaki', hex: '#D2B48C' },
  { name: 'Charcoal', hex: '#36454F' },
  { name: 'Slate', hex: '#708090' },
  { name: 'Stone', hex: '#B8B8A8' },
  { name: 'Heather Red', hex: '#C94C4C' },
  { name: 'Heather Royal', hex: '#3A5FCD' },
  { name: 'Heather Navy', hex: '#2C3E50' },
  { name: 'Heather Military Green', hex: '#556B2F' },
  { name: 'Heather Brown', hex: '#7B3F00' },
  { name: 'Heather Purple', hex: '#7E57C2' },
  { name: 'Heather Orange', hex: '#FF8C42' },
  { name: 'Heather Sapphire', hex: '#1363DF' },
  { name: 'Heather Cardinal', hex: '#A52A2A' },
  { name: 'Heather Forest', hex: '#228B22' },
]
